# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_auto_20161211_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='poster',
        ),
    ]
